title: Sparkling Resin Delights
description: Beautiful Handcrafted Resin Jewelry, Beaded Pens & Keychains
url: "https://sparklingresindelights.co.uk"

# This activates the clean, official GitHub minimalist theme as your background framework
theme: jekyll-theme-minimal
